name: Release VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: semantic
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release && echo "released=true" >> $GITHUB_ENV

      - name: Install vsce
        if: env.released == 'true'
        run: npm install -g @vscode/vsce

      - name: Publish to VSCode Marketplace
        if: env.released == 'true'
        continue-on-error: false
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish --no-verify -p $VSCE_PAT --logLevel debug
